// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire

package bootstrap

import (
	"github.com/gin-gonic/gin"
	"github.com/imankit007/url-shortner/controller"
	"github.com/imankit007/url-shortner/infrastructure"
	"github.com/imankit007/url-shortner/middleware"
	"github.com/imankit007/url-shortner/repository"
	"github.com/imankit007/url-shortner/service"
	"github.com/imankit007/url-shortner/utils/counter"
)

func InitializeRouter() (*gin.Engine, error) {
	authServicePublicKey, err := infrastructure.NewAuthServicePublicKey()
	if err != nil {
		return nil, err
	}
	authTokenIssuer := infrastructure.NewAuthTokenIssuer()
	mongoClient, err := infrastructure.NewMongoClient()
	if err != nil {
		return nil, err
	}
	urlCollection := infrastructure.NewURLCollection(mongoClient)
	redisClient := infrastructure.NewRedisClient()
	mongoURLRepository := repository.NewMongoURLRepository(urlCollection)
	urlRepository := repository.NewCachedURLRepository(mongoURLRepository, redisClient)
	hashIDEncoder, err := NewHashIDEncoder()
	if err != nil {
		return nil, err
	}
	urlCodeCounter := counter.NewURLCodeCounter(redisClient)
	applicationBaseURL := NewApplicationBaseURL()
	tokenAuthenticationService := service.NewTokenAuthenticationService(authServicePublicKey, authTokenIssuer)
	jwtAuthenticationMiddleware := middleware.NewJWTAuthenticationMiddleware(tokenAuthenticationService)
	urlService := service.NewURLService(urlRepository, hashIDEncoder, urlCodeCounter, applicationBaseURL)
	urlController := controller.NewURLController(urlService)
	engine := NewRouter(urlController, jwtAuthenticationMiddleware)
	return engine, nil
}
